package com.gravical.bwell.models;
// Generated 13-Feb-2013 01:12:06 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Media generated by hbm2java
 */
public class Media  implements java.io.Serializable {


     private int mediaId;
     private Date mediaStart;
     private Date mediaEnd;
     private String mediaFilename;
     private String mediaLocation;
     private String mediaDescription;
     private Integer sessionId;

    public Media() {
    }

	
    public Media(int mediaId, Date mediaStart, Date mediaEnd, String mediaLocation, String mediaDescription) {
        this.mediaId = mediaId;
        this.mediaStart = mediaStart;
        this.mediaEnd = mediaEnd;
        this.mediaLocation = mediaLocation;
        this.mediaDescription = mediaDescription;
    }
    public Media(int mediaId, Date mediaStart, Date mediaEnd, String mediaFilename, String mediaLocation, String mediaDescription, Integer sessionId) {
       this.mediaId = mediaId;
       this.mediaStart = mediaStart;
       this.mediaEnd = mediaEnd;
       this.mediaFilename = mediaFilename;
       this.mediaLocation = mediaLocation;
       this.mediaDescription = mediaDescription;
       this.sessionId = sessionId;
    }
   
    public int getMediaId() {
        return this.mediaId;
    }
    
    public void setMediaId(int mediaId) {
        this.mediaId = mediaId;
    }
    public Date getMediaStart() {
        return this.mediaStart;
    }
    
    public void setMediaStart(Date mediaStart) {
        this.mediaStart = mediaStart;
    }
    public Date getMediaEnd() {
        return this.mediaEnd;
    }
    
    public void setMediaEnd(Date mediaEnd) {
        this.mediaEnd = mediaEnd;
    }
    public String getMediaFilename() {
        return this.mediaFilename;
    }
    
    public void setMediaFilename(String mediaFilename) {
        this.mediaFilename = mediaFilename;
    }
    public String getMediaLocation() {
        return this.mediaLocation;
    }
    
    public void setMediaLocation(String mediaLocation) {
        this.mediaLocation = mediaLocation;
    }
    public String getMediaDescription() {
        return this.mediaDescription;
    }
    
    public void setMediaDescription(String mediaDescription) {
        this.mediaDescription = mediaDescription;
    }
    public Integer getSessionId() {
        return this.sessionId;
    }
    
    public void setSessionId(Integer sessionId) {
        this.sessionId = sessionId;
    }




}


