package com.gravical.bwell.models;
// Generated 12-Feb-2013 23:08:00 by Hibernate Tools 3.2.1.GA



/**
 * Roles generated by hbm2java
 */
public class Roles  implements java.io.Serializable {


     private int roleId;
     private String roleName;

    public Roles() {
    }

	
    public Roles(int roleId) {
        this.roleId = roleId;
    }
    public Roles(int roleId, String roleName) {
       this.roleId = roleId;
       this.roleName = roleName;
    }
   
    public int getRoleId() {
        return this.roleId;
    }
    
    public void setRoleId(int roleId) {
        this.roleId = roleId;
    }
    public String getRoleName() {
        return this.roleName;
    }
    
    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }

    @Override 
    public String toString() {
        return "["+this.roleId+";"+this.roleName+"]";
    }


}


