package com.gravical.bwell.models;
// Generated 19-Feb-2013 01:44:26 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Sessions generated by hbm2java
 */
public class Sessions  implements java.io.Serializable {


     private int sessionId;
     private Date sessionStart;
     private Date sessionEnd;
     private int sessionInitiator;
     private int sessionParticipant1Id;
     private int sessionParticipant2Id;
     private int sessionParticipant3Id;
     private String sessionDescription;
     private String sessionSummary;

    public Sessions() {
    }

	
    public Sessions(int sessionId, Date sessionStart, int sessionInitiator, int sessionParticipant1Id, int sessionParticipant2Id, int sessionParticipant3Id, String sessionDescription, String sessionSummary) {
        this.sessionId = sessionId;
        this.sessionStart = sessionStart;
        this.sessionInitiator = sessionInitiator;
        this.sessionParticipant1Id = sessionParticipant1Id;
        this.sessionParticipant2Id = sessionParticipant2Id;
        this.sessionParticipant3Id = sessionParticipant3Id;
        this.sessionDescription = sessionDescription;
        this.sessionSummary = sessionSummary;
    }
    public Sessions(int sessionId, Date sessionStart, Date sessionEnd, int sessionInitiator, int sessionParticipant1Id, int sessionParticipant2Id, int sessionParticipant3Id, String sessionDescription, String sessionSummary) {
       this.sessionId = sessionId;
       this.sessionStart = sessionStart;
       this.sessionEnd = sessionEnd;
       this.sessionInitiator = sessionInitiator;
       this.sessionParticipant1Id = sessionParticipant1Id;
       this.sessionParticipant2Id = sessionParticipant2Id;
       this.sessionParticipant3Id = sessionParticipant3Id;
       this.sessionDescription = sessionDescription;
       this.sessionSummary = sessionSummary;
    }
   
    public int getSessionId() {
        return this.sessionId;
    }
    
    public void setSessionId(int sessionId) {
        this.sessionId = sessionId;
    }
    public Date getSessionStart() {
        return this.sessionStart;
    }
    
    public void setSessionStart(Date sessionStart) {
        this.sessionStart = sessionStart;
    }
    public Date getSessionEnd() {
        return this.sessionEnd;
    }
    
    public void setSessionEnd(Date sessionEnd) {
        this.sessionEnd = sessionEnd;
    }
    public int getSessionInitiator() {
        return this.sessionInitiator;
    }
    
    public void setSessionInitiator(int sessionInitiator) {
        this.sessionInitiator = sessionInitiator;
    }
    public int getSessionParticipant1Id() {
        return this.sessionParticipant1Id;
    }
    
    public void setSessionParticipant1Id(int sessionParticipant1Id) {
        this.sessionParticipant1Id = sessionParticipant1Id;
    }
    public int getSessionParticipant2Id() {
        return this.sessionParticipant2Id;
    }
    
    public void setSessionParticipant2Id(int sessionParticipant2Id) {
        this.sessionParticipant2Id = sessionParticipant2Id;
    }
    public int getSessionParticipant3Id() {
        return this.sessionParticipant3Id;
    }
    
    public void setSessionParticipant3Id(int sessionParticipant3Id) {
        this.sessionParticipant3Id = sessionParticipant3Id;
    }
    public String getSessionDescription() {
        return this.sessionDescription;
    }
    
    public void setSessionDescription(String sessionDescription) {
        this.sessionDescription = sessionDescription;
    }
    public String getSessionSummary() {
        return this.sessionSummary;
    }
    
    public void setSessionSummary(String sessionSummary) {
        this.sessionSummary = sessionSummary;
    }




}


