package com.gravical.bwell.models;
// Generated Feb 8, 2013 4:26:48 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name="USERS"
    ,schema="BWELL"
)
public class Users  implements java.io.Serializable {


     private int userId;
     private String username;
     private String firstName;
     private String lastName;
     private String passwordHashed;
     private Integer roleId;

    public Users() {
    }

	
    public Users(int userId) {
        this.userId = userId;
    }
    public Users(int userId, String username, String firstName, String lastName, String passwordHashed, Integer roleId) {
       this.userId = userId;
       this.username = username;
       this.firstName = firstName;
       this.lastName = lastName;
       this.passwordHashed = passwordHashed;
       this.roleId = roleId;
    }
   
     @Id 
    
    @Column(name="USER_ID", unique=true, nullable=false, precision=5, scale=0)
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }
    
    @Column(name="USERNAME", length=15)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    
    @Column(name="FIRST_NAME", length=80)
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    
    @Column(name="LAST_NAME")
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    
    @Column(name="PASSWORD_HASHED", length=128)
    public String getPasswordHashed() {
        return this.passwordHashed;
    }
    
    public void setPasswordHashed(String passwordHashed) {
        this.passwordHashed = passwordHashed;
    }
    
    @Column(name="ROLE_ID", precision=5, scale=0)
    public Integer getRoleId() {
        return this.roleId;
    }
    
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }




}


