-- Create table SESSIONS

create table "BWELL".SESSIONS
(
	SESSION_ID NUMERIC(5) not null primary key,
	SESSION_START TIMESTAMP not null,
	SESSION_END TIMESTAMP not null,
	SESSION_INITIATOR NUMERIC(5) not null,
	SESSION_PARTICIPANT1_ID NUMERIC(5) not null,
	SESSION_PARTICIPANT2_ID NUMERIC(5) not null,
	SESSION_PARTICIPANT3_ID NUMERIC(5) not null,
	SESSION_DESCRIPTION VARCHAR(255) not null,
	SESSION_SUMMARY VARCHAR(255) not null
)
