-- SQL script to populate table BWELL.ROLES

DELETE FROM ROLES;

INSERT INTO ROLES VALUES (1,'Admin');
INSERT INTO ROLES VALUES (2,'Supervisor');
INSERT INTO ROLES VALUES (3,'Intern');
INSERT INTO ROLES VALUES (4,'Client');
INSERT INTO ROLES VALUES (5,'Guest');

