/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.gravical.bwell.views;

import com.gravical.bwell.db.HibernateUtil;
import com.gravical.bwell.models.Roles;
import java.awt.event.ActionListener;
import java.util.Iterator;
import java.util.List;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import org.hibernate.HibernateException;
import org.hibernate.Query;
import org.hibernate.Session;
import org.hibernate.SessionFactory;

/**
 *
 * @author user
 */
public class AdminRolesPanel extends javax.swing.JPanel {

    private static String QUERY_ALL_ROLES = "from Roles order by role_id";
    private static List rolesList;
    private static Session session;
        
    /**
     * Creates new form AdminRoles
     */
    public AdminRolesPanel() {
        initComponents();
        loadRoles();
        resultsTable.setColumnSelectionAllowed(false);
    }

    public void mainMenuButtonActionListener(ActionListener a) {
        this.MainMenuButton.addActionListener(a);
    }    

    public void adminMenuButtonActionListener(ActionListener a) {
        this.AdminHomeButton.addActionListener(a);
    }    

    // will call        loadRoles(QUERY_ALL_ROLES);
    public void executeRolesQueryActionListener(ActionListener a) {
        this.showRolesButton.addActionListener(a);
    }
    
    public void updateQueryActionListener(ActionListener a) {
        this.updateQuery.addActionListener(a);
    }
    
    public void loadRoles() {
    try {
        System.out.println("executeHQLQuery started");
        session = HibernateUtil.getSessionFactory().openSession();
        session.beginTransaction();
        Query q = session.createQuery(getQUERY_ALL_ROLES());
        List resultList = q.list();
        rolesList = resultList;
        displayResult(rolesList);
        session.getTransaction().commit();
    } catch (HibernateException he) {
        System.out.println("executeHQLQuery failed");
        he.printStackTrace();
    }
}  

private void displayResult(List resultList) {
    // TODO: update Vector to ArrayList
    Vector<String> tableHeaders = new Vector<String>();
    Vector tableData = new Vector();
    tableHeaders.add("Role ID"); 
    tableHeaders.add("Role Name"); 

    for(Object o : resultList) {
        Roles roles = (Roles)o;
        Vector<Object> oneRow = new Vector<Object>();
        oneRow.add(roles.getRoleId() );
        oneRow.add(roles.getRoleName());
        tableData.add(oneRow);
    }
    resultsTable.setModel(new DefaultTableModel(tableData, tableHeaders));   
}

public void saveChanges() {
        System.out.println("updateQuery ran");
        List newRolesList;
        Roles role = new Roles();

        //System.out.println("updateQuery role=" + role);
        //System.out.println("updateQuery (String) resultsTable.getValueAt(0, 1) =" + (String) resultsTable.getValueAt(0, 1));
        
        

        HibernateUtil.getSessionFactory().openSession();
        Session session = HibernateUtil.getSessionFactory().getCurrentSession();
        session.beginTransaction();
        for (int i=0;i<rolesList.size();i++) {
            role = (Roles) rolesList.get(i);
            role.setRoleName( (String) resultsTable.getValueAt(i, 1) );
            session.update(role);
        }
        session.getTransaction().commit();
        //displayResult(rolesList);        
        //session.close();
}

    /**
     * @return the QUERY_ALL_ROLES
     */
    public String getQUERY_ALL_ROLES() {
        return QUERY_ALL_ROLES;
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        AdminHomeButton = new javax.swing.JButton();
        MainMenuButton = new javax.swing.JButton();
        showRolesButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        resultsTable = new javax.swing.JTable();
        updateQuery = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Edit Roles");

        AdminHomeButton.setText("Admin Home");

        MainMenuButton.setText("Home");

        showRolesButton.setText("Query");

        resultsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Role ID", "Role Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        resultsTable.setColumnSelectionAllowed(true);
        resultsTable.getTableHeader().setReorderingAllowed(false);
        resultsTable.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                resultsTableFocusLost(evt);
            }
        });
        jScrollPane1.setViewportView(resultsTable);
        resultsTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        resultsTable.getColumnModel().getColumn(0).setResizable(false);
        resultsTable.getColumnModel().getColumn(1).setResizable(false);

        updateQuery.setText("Save Changes");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(AdminHomeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(MainMenuButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(168, 168, 168)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(showRolesButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(updateQuery, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(65, 65, 65))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AdminHomeButton)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(MainMenuButton))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(showRolesButton)
                        .addGap(32, 32, 32)
                        .addComponent(updateQuery))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(311, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void resultsTableFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_resultsTableFocusLost
        
        // TODO add your handling code here:
        saveChanges();
    }//GEN-LAST:event_resultsTableFocusLost

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AdminHomeButton;
    private javax.swing.JButton MainMenuButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable resultsTable;
    private javax.swing.JButton showRolesButton;
    private javax.swing.JButton updateQuery;
    // End of variables declaration//GEN-END:variables
}
