package com.gravical.bwell.views;

import java.awt.event.*;

public class Frame extends javax.swing.JFrame {
  public void setOutputText(String text) {
    output.setText(text);
  }

  public void addNextActionListener(ActionListener a) {
    next.addActionListener(a);
  }

  public void addResetActionListener(ActionListener a) {
    reset.addActionListener(a);
  }

  /** Creates new form Frame */
  public Frame() {
    initComponents();
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        next = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        output = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.FlowLayout());

        next.setText("Next");
        getContentPane().add(next);

        reset.setText("Reset");
        getContentPane().add(reset);

        output.setColumns(10);
        getContentPane().add(output);

        pack();
    }// </editor-fold>//GEN-END:initComponents

  /**
   * @param args the command line arguments
   */
/*
  public static void main(String args[]) {
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new Frame().setVisible(true);
      }
    });
  }
  */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton next;
    private javax.swing.JTextField output;
    private javax.swing.JButton reset;
    // End of variables declaration//GEN-END:variables
}
