/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.gravical.bwell.views;

import com.gravical.bwell.db.HibernateUtil;
import com.gravical.bwell.models.Sessions;
import java.awt.event.ActionListener;
import java.util.List;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import org.hibernate.HibernateException;
import org.hibernate.Query;
import org.hibernate.Session;

/**
 *
 * @author User
 */
public class SupervisePanel extends javax.swing.JPanel {
    private static String QUERY_ACTIVE_BWELL_SESSIONS = "from Sessions WHERE SESSION_END IS NULL";
    private static List bwellSessionsList;
    private static Session session;

    /**
     * Creates new form SupervisePanel
     */
    public SupervisePanel() {
        initComponents();
        loadBwellSessions();
    }

    public void loadBwellSessions() {
        try {
            System.out.println("executeHQLQuery started");
            session = HibernateUtil.getSessionFactory().openSession();
            session.beginTransaction();
            Query q = session.createQuery(QUERY_ACTIVE_BWELL_SESSIONS);
            List resultList = q.list();
            bwellSessionsList = resultList;
            displayResult(bwellSessionsList);
            session.getTransaction().commit();
        } catch (HibernateException he) {
            System.out.println("executeHQLQuery failed");
            he.printStackTrace();
        }
    }

    private void displayResult(List resultList) {
        // TODO: update Vector to ArrayList
        Vector<String> tableHeaders = new Vector<String>();
        Vector tableData = new Vector();
        tableHeaders.add("Encounter ID");
        tableHeaders.add("Start");
        tableHeaders.add("End");
        tableHeaders.add("Description");

        for (Object o : resultList) {
            Sessions bwellSession = (Sessions) o;
            Vector<Object> oneRow = new Vector<Object>();
            oneRow.add(bwellSession.getSessionId());
            oneRow.add(bwellSession.getSessionStart());
            oneRow.add(bwellSession.getSessionEnd());
            oneRow.add(bwellSession.getSessionDescription());

            tableData.add(oneRow);
        }
        activeBWellSessions.setModel(new DefaultTableModel(tableData, tableHeaders));
    }
    
    
    
    public void HomeButtonActionListener(ActionListener a) {
        HomeButton.addActionListener(a);
    }    

    public void UserProfileButtonActionListener(ActionListener a) {
        UserProfileButton.addActionListener(a);
    }    

    public void SettingsButtonActionListener(ActionListener a) {
        SettingsButton.addActionListener(a);
    }    

    public void LogoutButtonActionListener(ActionListener a) {
        LogoutButton.addActionListener(a);
    }    

    public void HelpButtonActionListener(ActionListener a) {
        HelpButton.addActionListener(a);
    }    
    
    public void SuperviseEncounterButtonActionListener(ActionListener a) {
        SuperviseEncounterButton.addActionListener(a);
    }    

    public void ForceCloseButtonActionListener(ActionListener a) {
        ForceCloseButton.addActionListener(a);
    }    

    public void CancelButtonActionListener(ActionListener a) {
        CancelButton.addActionListener(a);
    }    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SettingsButton = new javax.swing.JButton();
        UserProfileButton = new javax.swing.JButton();
        HomeButton = new javax.swing.JButton();
        LogoutButton = new javax.swing.JButton();
        HelpButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nameForSearchField = new javax.swing.JTextField();
        InternsDropdownField = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        activeBWellSessions = new javax.swing.JTable();
        SuperviseEncounterButton = new javax.swing.JButton();
        ForceCloseButton = new javax.swing.JButton();
        CancelButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        SettingsButton.setText("Settings");

        UserProfileButton.setText("User Profile");

        HomeButton.setText("Home");

        LogoutButton.setText("Logout");

        HelpButton.setText("Help");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Supervise Active Encounter");

        jLabel2.setText("Name:");

        nameForSearchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameForSearchFieldActionPerformed(evt);
            }
        });

        InternsDropdownField.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Intern 1", "Intern 2", "Intern 3" }));

        activeBWellSessions.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title", "Description", "Started At"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(activeBWellSessions);
        activeBWellSessions.getColumnModel().getColumn(0).setResizable(false);
        activeBWellSessions.getColumnModel().getColumn(1).setResizable(false);
        activeBWellSessions.getColumnModel().getColumn(2).setResizable(false);

        SuperviseEncounterButton.setText("Supervise");

        ForceCloseButton.setText("Force Close");

        CancelButton.setText("Cancel");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 356, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 117, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(HomeButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(UserProfileButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(SettingsButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(LogoutButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(HelpButton))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(nameForSearchField, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(24, 24, 24)
                                                .addComponent(InternsDropdownField, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(47, 47, 47)
                                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(SuperviseEncounterButton)
                        .addGap(28, 28, 28)
                        .addComponent(ForceCloseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(CancelButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(HomeButton)
                            .addComponent(UserProfileButton)
                            .addComponent(SettingsButton)
                            .addComponent(LogoutButton)
                            .addComponent(HelpButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(nameForSearchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(InternsDropdownField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SuperviseEncounterButton)
                    .addComponent(ForceCloseButton)
                    .addComponent(CancelButton))
                .addGap(23, 23, 23))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nameForSearchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameForSearchFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameForSearchFieldActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelButton;
    private javax.swing.JButton ForceCloseButton;
    private javax.swing.JButton HelpButton;
    private javax.swing.JButton HomeButton;
    private javax.swing.JComboBox InternsDropdownField;
    private javax.swing.JButton LogoutButton;
    private javax.swing.JButton SettingsButton;
    private javax.swing.JButton SuperviseEncounterButton;
    private javax.swing.JButton UserProfileButton;
    private javax.swing.JTable activeBWellSessions;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nameForSearchField;
    // End of variables declaration//GEN-END:variables
}
