/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.gravical.bwell.views;

import com.gravical.bwell.controller.MVCController;
import com.gravical.bwell.db.HibernateUtil;
import com.gravical.bwell.models.Users;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import org.hibernate.HibernateException;
import org.hibernate.Query;
import org.hibernate.Session;

/**
 *
 * @author User
 */
public class UserAdministrationPanel extends javax.swing.JPanel {
    private static String QUERY_ALL_USERS = "from Users";    
    private static List usersList;
    private static Session session;

    /**
     * Creates new form UserAdministrationPanel
     */
    public UserAdministrationPanel() {
        initComponents();
        loadUsers();
        resultsTable.setColumnSelectionAllowed(false);

    }

    public void updatePanel() {
        int userSize = 0;
        userSize = MVCController.getUsers().size();

        this.userCount.setText("" + userSize);

    }

    public void HomeButtonActionListener(ActionListener a) {
        HomeButton.addActionListener(a);
    }

    public void LogoutButtonActionListener(ActionListener a) {
        LogoutButton.addActionListener(a);
    }

    public void UserProfileButtonActionListener(ActionListener a) {
        UserProfileButton.addActionListener(a);
    }

    public void SettingsButtonActionListener(ActionListener a) {
        SettingsButton.addActionListener(a);
    }

    public void editUserButtonActionListener(ActionListener a) {
        editUserButton.addActionListener(
                new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent ae) {
                         System.out.println("editUserButton pressed");
                    }
                });
    }

    public void addUserButtonActionListener(ActionListener a) {
        addUserButton.addActionListener(
                new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent ae) {
                        
                    }
                });
    }
    
    public void loadUsers() {
    try {        
        //System.out.println("executeHQLQuery started");
        session = HibernateUtil.getSessionFactory().openSession();
        session.beginTransaction();
        Query q = session.createQuery(this.QUERY_ALL_USERS);
        List resultList = q.list();
        usersList = resultList;
        displayResult(usersList);
        //session.getTransaction().commit();
    } catch (HibernateException he) {
        System.out.println("executeHQLQuery failed");
        he.printStackTrace();
    }
}  

private void displayResult(List resultList) {
    // TODO: update Vector to ArrayList
    Vector<String> tableHeaders = new Vector<String>();
    Vector tableData = new Vector();
    tableHeaders.add("Username"); 
    tableHeaders.add("Full Name"); 
    tableHeaders.add("Role"); 

    for(Object o : resultList) {
        Users users = (Users)o;
        Vector<Object> oneRow = new Vector<Object>();
        oneRow.add(users.getUsername());
        oneRow.add(users.getLastName() +", "+ users.getFirstName() );
        oneRow.add(users.getRoleId());
        
        tableData.add(oneRow);
    }
    resultsTable.setModel(new DefaultTableModel(tableData, tableHeaders));   
}
    
    
    // Listen for user request to go to Home, aka Main Menu
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HomeButton = new javax.swing.JButton();
        UserProfileButton = new javax.swing.JButton();
        SettingsButton = new javax.swing.JButton();
        LogoutButton = new javax.swing.JButton();
        HelpButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        resultsTable = new javax.swing.JTable();
        userCountLabel = new javax.swing.JLabel();
        userCount = new javax.swing.JLabel();
        userAdministrationLabel = new javax.swing.JLabel();
        addUserButton = new javax.swing.JButton();
        editUserButton = new javax.swing.JButton();
        activateUserButton = new javax.swing.JButton();
        editPolicyButton = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(800, 600));

        HomeButton.setText("Home");

        UserProfileButton.setText("User Profile");

        SettingsButton.setText("Settings");

        LogoutButton.setText("Logout");

        HelpButton.setText("Help");

        resultsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Active", "Username", "Real Name", "Roles"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        resultsTable.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(resultsTable);
        resultsTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        resultsTable.getColumnModel().getColumn(0).setResizable(false);
        resultsTable.getColumnModel().getColumn(0).setPreferredWidth(4);
        resultsTable.getColumnModel().getColumn(0).setHeaderValue("Active");
        resultsTable.getColumnModel().getColumn(1).setResizable(false);
        resultsTable.getColumnModel().getColumn(1).setPreferredWidth(12);
        resultsTable.getColumnModel().getColumn(1).setHeaderValue("Username");
        resultsTable.getColumnModel().getColumn(2).setResizable(false);
        resultsTable.getColumnModel().getColumn(2).setPreferredWidth(12);
        resultsTable.getColumnModel().getColumn(2).setHeaderValue("Real Name");
        resultsTable.getColumnModel().getColumn(3).setResizable(false);
        resultsTable.getColumnModel().getColumn(3).setPreferredWidth(10);
        resultsTable.getColumnModel().getColumn(3).setHeaderValue("Roles");

        userCountLabel.setText("User Count:");

        userCount.setText("0");

        userAdministrationLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        userAdministrationLabel.setText("User Administration");

        addUserButton.setText("Add User");

        editUserButton.setText("Edit User");

        activateUserButton.setText("Activate User");

        editPolicyButton.setText("Edit Policy");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(HomeButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(UserProfileButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(SettingsButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LogoutButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(HelpButton)
                        .addGap(115, 115, 115)
                        .addComponent(userCountLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(userCount))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(243, 243, 243)
                        .addComponent(userAdministrationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(addUserButton)
                                .addGap(34, 34, 34)
                                .addComponent(editUserButton)
                                .addGap(32, 32, 32)
                                .addComponent(activateUserButton)
                                .addGap(31, 31, 31)
                                .addComponent(editPolicyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 634, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(125, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HomeButton)
                    .addComponent(UserProfileButton)
                    .addComponent(SettingsButton)
                    .addComponent(LogoutButton)
                    .addComponent(HelpButton)
                    .addComponent(userCountLabel)
                    .addComponent(userCount))
                .addGap(18, 18, 18)
                .addComponent(userAdministrationLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addUserButton)
                    .addComponent(editUserButton)
                    .addComponent(activateUserButton)
                    .addComponent(editPolicyButton))
                .addContainerGap(280, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton HelpButton;
    private javax.swing.JButton HomeButton;
    private javax.swing.JButton LogoutButton;
    private javax.swing.JButton SettingsButton;
    private javax.swing.JButton UserProfileButton;
    private javax.swing.JButton activateUserButton;
    private javax.swing.JButton addUserButton;
    private javax.swing.JButton editPolicyButton;
    private javax.swing.JButton editUserButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable resultsTable;
    private javax.swing.JLabel userAdministrationLabel;
    private javax.swing.JLabel userCount;
    private javax.swing.JLabel userCountLabel;
    // End of variables declaration//GEN-END:variables
}
