/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.gravical.bwell.views;

import com.gravical.bwell.controller.MVCController;
import com.gravical.bwell.models.Users;
import java.awt.event.ActionListener;

/**
 *
 * @author User
 */
public class UserAdministrationPanel extends javax.swing.JPanel {
    
    
    
    /**
     * Creates new form UserAdministrationPanel
     */
    public UserAdministrationPanel() {
        initComponents();
        //int userCount = MVCController.getUsers().size();
        
    }

    public void updatePanel() {
        int userSize = 0;
        userSize = MVCController.getUsers().size();
        
        this.userCount.setText("" + userSize);
        
    }
    
    public void HomeButtonActionListener(ActionListener a) {
        HomeButton.addActionListener(a);
    }    

    public void LogoutButtonActionListener(ActionListener a) {
        LogoutButton.addActionListener(a);
    }    
    
    public void UserProfileButtonActionListener(ActionListener a) {
        UserProfileButton.addActionListener(a);
    }    
    
    public void SettingsButtonActionListener(ActionListener a) {
        SettingsButton.addActionListener(a);
    }    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HomeButton = new javax.swing.JButton();
        UserProfileButton = new javax.swing.JButton();
        SettingsButton = new javax.swing.JButton();
        LogoutButton = new javax.swing.JButton();
        HelpButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        userCountLabel = new javax.swing.JLabel();
        userCount = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(800, 600));

        HomeButton.setText("Home");

        UserProfileButton.setText("User Profile");

        SettingsButton.setText("Settings");

        LogoutButton.setText("Logout");

        HelpButton.setText("Help");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Active", "Username", "Real Name", "Roles"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable1.getColumnModel().getColumn(0).setResizable(false);
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(4);
        jTable1.getColumnModel().getColumn(0).setHeaderValue("Active");
        jTable1.getColumnModel().getColumn(1).setResizable(false);
        jTable1.getColumnModel().getColumn(1).setPreferredWidth(12);
        jTable1.getColumnModel().getColumn(1).setHeaderValue("Username");
        jTable1.getColumnModel().getColumn(2).setResizable(false);
        jTable1.getColumnModel().getColumn(2).setPreferredWidth(12);
        jTable1.getColumnModel().getColumn(2).setHeaderValue("Real Name");
        jTable1.getColumnModel().getColumn(3).setResizable(false);
        jTable1.getColumnModel().getColumn(3).setPreferredWidth(10);
        jTable1.getColumnModel().getColumn(3).setHeaderValue("Roles");

        userCountLabel.setText("User Count:");

        userCount.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(HomeButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(UserProfileButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(SettingsButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LogoutButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(HelpButton)
                        .addGap(115, 115, 115)
                        .addComponent(userCountLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(userCount))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 634, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(165, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HomeButton)
                    .addComponent(UserProfileButton)
                    .addComponent(SettingsButton)
                    .addComponent(LogoutButton)
                    .addComponent(HelpButton)
                    .addComponent(userCountLabel)
                    .addComponent(userCount))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton HelpButton;
    private javax.swing.JButton HomeButton;
    private javax.swing.JButton LogoutButton;
    private javax.swing.JButton SettingsButton;
    private javax.swing.JButton UserProfileButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel userCount;
    private javax.swing.JLabel userCountLabel;
    // End of variables declaration//GEN-END:variables
}
